"""Supervised finetuning data: conversation sources and packed, masked batches.

Pretraining streams undifferentiated text; SFT streams *conversations*, and the
two differ in one way that matters for the data pipeline. A conversation is an
indivisible unit — split it across two rows and the second row trains the model
to answer a question it never saw — so rows are packed rather than cut from a
continuous stream.

The packer here follows nanochat's ``sft_data_generator_bos_bestfit``: every row
begins at a conversation boundary, conversations are placed best-fit into the
remaining space, and whatever space is left over is padded rather than filled
with a truncated conversation. Padding costs a little compute; discarding tokens
costs data. Padded positions and all non-assistant tokens carry ``ignore_index``
targets, so neither reaches the loss.
"""

from __future__ import annotations

import random
import re
from typing import Any, Callable, Iterator, Sequence

import torch
import torch.distributed as dist
from torch.utils.data import IterableDataset, get_worker_info
from transformers import PreTrainedTokenizerBase

from ohara.chat import IGNORE_INDEX, render_conversation


Conversation = dict[str, Any]
ConversationSource = Callable[[], Sequence[Conversation]]

MC_LETTERS = ("A", "B", "C", "D")


# -----------------------------------------------------------------------------
# Conversation sources
#
# Each returns a list of {"messages": [...]} dicts. They are loaded eagerly
# because the SFT mixture is small (hundreds of thousands of rows) and the
# packer needs random access to shuffle and to refill its best-fit buffer.


def _load(dataset_name: str, config: str | None, split: str, cache_dir: str | None):
    from datasets import load_dataset

    kwargs: dict[str, Any] = {"path": dataset_name, "split": split, "cache_dir": cache_dir}
    if config is not None:
        kwargs["name"] = config
    return load_dataset(**kwargs)


def smoltalk_conversations(
    split: str = "train",
    *,
    limit: int | None = None,
    cache_dir: str | None = None,
) -> list[Conversation]:
    """General-purpose conversations from HuggingFaceTB/smol-smoltalk.

    The "smol" variant is generated by a smaller model, which makes it a better
    imitation target for the models this repo trains than full SmolTalk.
    """
    if split not in {"train", "test"}:
        raise ValueError("smoltalk split must be 'train' or 'test'")
    dataset = _load("HuggingFaceTB/smol-smoltalk", None, split, cache_dir)
    conversations: list[Conversation] = []
    for row in dataset:
        messages = row["messages"]
        if len(messages) < 2:
            continue
        conversations.append({"messages": [dict(message) for message in messages]})
        if limit is not None and len(conversations) >= limit:
            break
    return conversations


_GSM8K_TOOL_CALL = re.compile(r"(<<[^>]+>>)")


def gsm8k_conversations(
    split: str = "train",
    *,
    limit: int | None = None,
    cache_dir: str | None = None,
    use_tool_calls: bool = True,
) -> list[Conversation]:
    """Grade-school math with GSM8K's ``<<expr=result>>`` calculator annotations.

    With ``use_tool_calls`` the annotations become python/python_output parts, so
    the model learns to emit an expression and then *read back* a result it did
    not compute. Otherwise they are stripped and the solution trains as plain
    text.
    """
    if split not in {"train", "test"}:
        raise ValueError("gsm8k split must be 'train' or 'test'")
    dataset = _load("openai/gsm8k", "main", split, cache_dir)
    conversations: list[Conversation] = []
    for row in dataset:
        question, answer = row["question"], row["answer"]
        if use_tool_calls:
            parts: list[dict[str, str]] = []
            for chunk in _GSM8K_TOOL_CALL.split(answer):
                if chunk.startswith("<<") and chunk.endswith(">>"):
                    inner = chunk[2:-2]
                    expression, _, result = inner.rpartition("=")
                    if not expression:
                        expression, result = inner, ""
                    parts.append({"type": "python", "text": expression})
                    parts.append({"type": "python_output", "text": result})
                elif chunk:
                    parts.append({"type": "text", "text": chunk})
            content: Any = parts
        else:
            content = _GSM8K_TOOL_CALL.sub("", answer)
        conversations.append(
            {
                "messages": [
                    {"role": "user", "content": question},
                    {"role": "assistant", "content": content},
                ]
            }
        )
        if limit is not None and len(conversations) >= limit:
            break
    return conversations


def render_multiple_choice(question: str, choices: Sequence[str]) -> str:
    """Render a multiple-choice prompt with the letter *after* each choice.

    Two details matter for small models: the letter trails the choice, which
    binds them more tightly, and there is no space before the letter, so the
    prompt's "A" is the same token as the "A" the assistant is trained to emit.
    """
    lines = "".join(
        f"- {choice}={letter}\n" for letter, choice in zip(MC_LETTERS, choices)
    )
    return (
        f"Multiple Choice question: {question}\n"
        f"{lines}\n"
        "Respond only with the letter of the correct answer."
    )


def mmlu_conversations(
    split: str = "auxiliary_train",
    *,
    limit: int | None = None,
    cache_dir: str | None = None,
) -> list[Conversation]:
    """MMLU rendered as single-letter answers, teaching the multiple-choice format."""
    valid = {"auxiliary_train", "validation", "dev", "test"}
    if split not in valid:
        raise ValueError(f"mmlu split must be one of {sorted(valid)}")
    dataset = _load("cais/mmlu", "all", split, cache_dir)
    conversations: list[Conversation] = []
    for row in dataset:
        choices = row["choices"]
        if len(choices) != len(MC_LETTERS):
            continue
        conversations.append(
            {
                "messages": [
                    {"role": "user", "content": render_multiple_choice(row["question"], choices)},
                    {"role": "assistant", "content": MC_LETTERS[int(row["answer"])]},
                ]
            }
        )
        if limit is not None and len(conversations) >= limit:
            break
    return conversations


def build_mixture(
    *,
    split: str = "train",
    smoltalk_limit: int | None = None,
    mmlu_epochs: int = 1,
    mmlu_limit: int | None = None,
    gsm8k_epochs: int = 1,
    gsm8k_limit: int | None = None,
    cache_dir: str | None = None,
    seed: int = 42,
) -> list[Conversation]:
    """Assemble and shuffle the SmolTalk + MMLU + GSM8K SFT mixture.

    ``*_epochs`` repeats a source, which is how nanochat upweights the two small
    task datasets against SmolTalk's 460K conversations without reweighting the
    sampler.
    """
    if split not in {"train", "val"}:
        raise ValueError("mixture split must be 'train' or 'val'")
    if mmlu_epochs < 0 or gsm8k_epochs < 0:
        raise ValueError("epoch counts cannot be negative")

    conversations: list[Conversation] = []
    if split == "train":
        conversations.extend(
            smoltalk_conversations("train", limit=smoltalk_limit, cache_dir=cache_dir)
        )
        for _ in range(mmlu_epochs):
            conversations.extend(
                mmlu_conversations("auxiliary_train", limit=mmlu_limit, cache_dir=cache_dir)
            )
        for _ in range(gsm8k_epochs):
            conversations.extend(
                gsm8k_conversations("train", limit=gsm8k_limit, cache_dir=cache_dir)
            )
    else:
        # Validation keeps roughly the training proportions so val loss stays
        # comparable across the run rather than drifting with the mixture.
        conversations.extend(
            smoltalk_conversations("test", limit=smoltalk_limit, cache_dir=cache_dir)
        )
        conversations.extend(
            mmlu_conversations("test", limit=mmlu_limit or 5_200, cache_dir=cache_dir)
        )
        conversations.extend(
            gsm8k_conversations("test", limit=gsm8k_limit or 420, cache_dir=cache_dir)
        )

    if not conversations:
        raise RuntimeError(f"SFT {split} mixture is empty")
    random.Random(seed).shuffle(conversations)
    return conversations


# -----------------------------------------------------------------------------
# Packing


class ConversationDataset(IterableDataset):
    """Pack rendered conversations into fixed-length rows with masked targets.

    Yields ``(inputs, targets)`` of shape ``(max_length,)``, ready for the same
    ``DataLoader`` and ``Trainer`` the pretraining path uses. ``targets`` is
    ``ignore_index`` everywhere except tokens an assistant turn should produce.

    Rows are filled best-fit from a lookahead buffer: take the longest remaining
    conversation that still fits. This keeps padding low without ever cutting a
    conversation in half. When nothing fits, the tail is padded.
    """

    def __init__(
        self,
        conversations: Sequence[Conversation],
        tokenizer: PreTrainedTokenizerBase,
        *,
        max_length: int,
        buffer_size: int = 100,
        ignore_index: int = IGNORE_INDEX,
        seed: int = 42,
        shuffle: bool = True,
        infinite: bool = True,
        data_rank: int | None = None,
        data_world_size: int | None = None,
    ) -> None:
        super().__init__()
        if max_length < 2:
            raise ValueError("max_length must be at least 2")
        if buffer_size < 1:
            raise ValueError("buffer_size must be at least 1")
        if not conversations:
            raise ValueError("conversations must not be empty")
        if (data_rank is None) != (data_world_size is None):
            raise ValueError("data_rank and data_world_size must be provided together")
        self.conversations = conversations
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.buffer_size = buffer_size
        self.ignore_index = ignore_index
        self.seed = seed
        self.shuffle = shuffle
        self.infinite = infinite
        self.data_rank = data_rank
        self.data_world_size = data_world_size
        # Rows hold max_length + 1 tokens; the shift into (inputs, targets) consumes one.
        self.row_capacity = max_length + 1
        self.pad_token_id = tokenizer.pad_token_id
        if self.pad_token_id is None:
            self.pad_token_id = tokenizer.eos_token_id
        if self.pad_token_id is None:
            raise ValueError("tokenizer must define a PAD or EOS token for padding")

    def _shard(self) -> tuple[int, int]:
        worker = get_worker_info()
        worker_id = worker.id if worker is not None else 0
        num_workers = worker.num_workers if worker is not None else 1
        rank, world_size = self.data_rank, self.data_world_size
        if rank is None or world_size is None:
            distributed = dist.is_available() and dist.is_initialized()
            rank = dist.get_rank() if distributed else 0
            world_size = dist.get_world_size() if distributed else 1
        return rank * num_workers + worker_id, world_size * num_workers

    def _rendered(self, epoch: int) -> Iterator[tuple[list[int], list[int]]]:
        """Yield (ids, mask) for this shard's conversations, skipping bad rows."""
        shard_id, num_shards = self._shard()
        order = list(range(len(self.conversations)))
        if self.shuffle:
            random.Random(self.seed + epoch).shuffle(order)
        for position, index in enumerate(order):
            if position % num_shards != shard_id:
                continue
            conversation = self.conversations[index]
            try:
                ids, mask = render_conversation(
                    self.tokenizer,
                    conversation["messages"],
                    max_tokens=self.row_capacity,
                )
            except ValueError:
                # Malformed conversations (bad role order, unknown part type)
                # are dropped rather than allowed to corrupt a training row.
                continue
            if len(ids) < 2 or not any(mask):
                # Nothing supervised in this row; it would contribute no gradient.
                continue
            yield ids, mask

    def __iter__(self) -> Iterator[tuple[torch.Tensor, torch.Tensor]]:
        epoch = 0
        while True:
            source = self._rendered(epoch)
            buffer: list[tuple[list[int], list[int]]] = []
            exhausted = False

            while True:
                while not exhausted and len(buffer) < self.buffer_size:
                    try:
                        buffer.append(next(source))
                    except StopIteration:
                        exhausted = True
                if not buffer:
                    break

                row_ids: list[int] = []
                row_mask: list[int] = []
                while buffer:
                    remaining = self.row_capacity - len(row_ids)
                    best_index = -1
                    best_length = -1
                    for index, (ids, _) in enumerate(buffer):
                        length = len(ids)
                        if length <= remaining and length > best_length:
                            best_index, best_length = index, length
                    if best_index < 0:
                        break
                    ids, mask = buffer.pop(best_index)
                    row_ids.extend(ids)
                    row_mask.extend(mask)
                    while not exhausted and len(buffer) < self.buffer_size:
                        try:
                            buffer.append(next(source))
                        except StopIteration:
                            exhausted = True

                if not row_ids:
                    # The next conversation alone exceeds a full row even after
                    # render-time truncation, which should not happen.
                    raise RuntimeError("conversation does not fit in a single row")

                padding = self.row_capacity - len(row_ids)
                if padding > 0:
                    row_ids.extend([self.pad_token_id] * padding)
                    row_mask.extend([0] * padding)

                inputs = torch.tensor(row_ids[:-1], dtype=torch.long)
                targets = torch.tensor(row_ids[1:], dtype=torch.long)
                supervised = torch.tensor(row_mask[1:], dtype=torch.bool)
                targets = torch.where(
                    supervised,
                    targets,
                    torch.full_like(targets, self.ignore_index),
                )
                yield inputs, targets

            if not self.infinite:
                return
            epoch += 1
